import { Injectable } from "@angular/core";
import { QuizzCard } from "../templates/quizz-card";

@Injectable({
    providedIn: 'root'
})

export class QuizzCardService{
    private quizzCards: QuizzCard[] = [
        new QuizzCard('botanique', 'facile', 'assets/bota.jpeg', 'Quel arbre produit des glands ?', 'chêne', new Date()),
        new QuizzCard('histoire', 'expert', 'assets/histo.jpg', 'Qui était le premier empereur romain ?', 'auguste', new Date()),
        new QuizzCard('zoo', 'génie', 'assets/zoo.jpeg', 'Quel est le plus grand mammifère terrestre ?', 'éléphant', new Date()),
        new QuizzCard('science et technologie', 'moyenne', 'assets/sci_tech.jpg', 'Quel est le langage de programmation le plus utilisé en IA ?', 'python', new Date()),
        new QuizzCard('géographie', 'facile', 'assets/geo.jpg', 'Quel est le plus long fleuve du monde ?', 'nil', new Date()),
        new QuizzCard('médecine', 'difficile', 'assets/med.jpeg', 'Quel spécialiste traite les maladies de la peau ?', 'dermatologue', new Date()),
        new QuizzCard('science et technologie', 'expert', 'assets/sci_tech.jpg', 'Quelle planète est la plus proche du soleil ?', 'mercure', new Date()),
        new QuizzCard('histoire', 'facile', 'assets/histo.jpg', 'Quelle guerre s’est terminée en 1945 ?', 'seconde guerre mondiale', new Date()),
        new QuizzCard('zoo', 'moyenne', 'assets/zoo.jpeg', 'Quel animal a une bosse et vit dans le désert ?', 'chameau', new Date()),
        new QuizzCard('géographie', 'génie', 'assets/geo.jpg', 'Quel est le plus grand désert du monde ?', 'antarctique', new Date()),
        new QuizzCard('botanique', 'expert', 'assets/bota.jpeg', 'Quel pigment rend les plantes vertes ?', 'chlorophylle', new Date()),
        new QuizzCard('médecine', 'moyenne', 'assets/med.jpeg', 'Quel organe est affecté par l\'hépatite ?', 'foie', new Date()),
        new QuizzCard('science et technologie', 'facile', 'assets/sci_tech.jpg', 'Quelle est l’unité de mesure de la résistance électrique ?', 'ohm', new Date()),
        new QuizzCard('zoo', 'difficile', 'assets/zoo.jpeg', 'Quel animal est connu pour son cou très long ?', 'girafe', new Date()),
        new QuizzCard('histoire', 'moyenne', 'assets/histo.jpg', 'Qui a découvert l\'Amérique ?', 'christophe colomb', new Date()),
        new QuizzCard('botanique', 'génie', 'assets/bota.jpeg', 'Quel gaz les plantes absorbent-elles ?', 'dioxyde de carbone', new Date()),
        new QuizzCard('géographie', 'expert', 'assets/geo.jpg', 'Quel pays a pour capitale Canberra ?', 'australie', new Date()),
        new QuizzCard('science et technologie', 'difficile', 'assets/sci_tech.jpg', 'Qui a inventé la machine à vapeur moderne ?', 'james watt', new Date()),
        new QuizzCard('médecine', 'facile', 'assets/med.jpeg', 'Comment s\'appelle le virus responsable du sida ?', 'vih', new Date()),
        new QuizzCard('zoo', 'expert', 'assets/zoo.jpeg', 'Quel oiseau ne vole pas mais court très vite ?', 'autruche', new Date()),
        new QuizzCard('histoire', 'facile', 'assets/histo.jpg', 'En quelle année a eu lieu la Révolution française ?', '1789', new Date()),
        new QuizzCard('science et technologie', 'difficile', 'assets/sci_tech.jpg', 'Quel est l’élément chimique dont le symbole est H ?', 'hydrogène', new Date()),
        new QuizzCard('médecine', 'génie', 'assets/med.jpeg', 'Quel est l’os le plus long du corps humain ?', 'fémur', new Date()),
        new QuizzCard('géographie', 'facile', 'assets/geo.jpg', 'Dans quel pays se trouve la ville de Kyoto ?', 'japon', new Date()),
        new QuizzCard('botanique', 'moyenne', 'assets/bota.jpeg', 'Quelle est la partie comestible de la carotte ?', 'racine', new Date()),
        new QuizzCard('zoo', 'moyenne', 'assets/zoo.jpeg', 'Quel animal est connu pour son cou très long ?', 'girafe', new Date()),
        new QuizzCard('science et technologie', 'expert', 'assets/sci_tech.jpg', 'Quelle planète est la plus proche du soleil ?', 'mercure', new Date()),
        new QuizzCard('histoire', 'moyenne', 'assets/histo.jpg', 'Qui a découvert l’Amérique ?', 'christophe colomb', new Date()),
        new QuizzCard('médecine', 'facile', 'assets/med.jpeg', 'Quel organe est affecté par l’hépatite ?', 'foie', new Date()),
        new QuizzCard('botanique', 'expert', 'assets/bota.jpeg', 'Quel arbre produit des glands ?', 'chêne', new Date()),
        new QuizzCard('zoo', 'génie', 'assets/zoo.jpeg', 'Quel oiseau ne vole pas mais court très vite ?', 'autruche', new Date()),
        new QuizzCard('géographie', 'génie', 'assets/geo.jpg', 'Quel est le plus grand désert du monde ?', 'antarctique', new Date()),
        new QuizzCard('histoire', 'expert', 'assets/histo.jpg', 'Quel roi a été guillotiné pendant la Révolution française ?', 'louis xvi', new Date()),
        new QuizzCard('science et technologie', 'facile', 'assets/sci_tech.jpg', 'Quel est le langage de programmation le plus utilisé en IA ?', 'python', new Date()),
        new QuizzCard('médecine', 'moyenne', 'assets/med.jpeg', 'Quel est le groupe sanguin universel ?', 'o-', new Date()),
        new QuizzCard('zoo', 'difficile', 'assets/zoo.jpeg', 'Quel animal a une bosse et vit dans le désert ?', 'chameau', new Date()),
        new QuizzCard('botanique', 'génie', 'assets/bota.jpeg', 'Quel pigment rend les plantes vertes ?', 'chlorophylle', new Date()),
        new QuizzCard('science et technologie', 'difficile', 'assets/sci_tech.jpg', 'Quel gaz est utilisé dans les écrans plasma ?', 'xénon', new Date()),
        new QuizzCard('histoire', 'moyenne', 'assets/histo.jpg', 'Qui a découvert l’Amérique ?', 'christophe colomb', new Date()),
        new QuizzCard('science et technologie', 'facile', 'assets/sci_tech.jpg', 'Quel est le gaz utilisé dans les écrans plasma ?', 'xénon', new Date()),
        new QuizzCard('histoire', 'expert', 'assets/histo.jpg', 'Qui était le premier empereur romain ?', 'auguste', new Date()),
        new QuizzCard('botanique', 'facile', 'assets/bota.jpeg', 'Quelle est la fleur emblématique du Japon ?', 'cerisier', new Date()),
        new QuizzCard('zoo', 'difficile', 'assets/zoo.jpeg', 'Quel est le plus grand mammifère terrestre ?', 'éléphant', new Date()),
        new QuizzCard('géographie', 'génie', 'assets/geo.jpg', 'Quel est le plus grand désert du monde ?', 'antarctique', new Date()),
        new QuizzCard('médecine', 'expert', 'assets/med.jpeg', 'Quel spécialiste traite les maladies de la peau ?', 'dermatologue', new Date()),
        new QuizzCard('histoire', 'moyenne', 'assets/histo.jpg', 'Qui a découvert l’Amérique ?', 'christophe colomb', new Date()),
        new QuizzCard('science et technologie', 'difficile', 'assets/sci_tech.jpg', 'Qui a inventé la machine à vapeur moderne ?', 'james watt', new Date()),
        new QuizzCard('botanique', 'moyenne', 'assets/bota.jpeg', 'Quelle est la partie comestible de la carotte ?', 'racine', new Date()),
        new QuizzCard('zoo', 'génie', 'assets/zoo.jpeg', 'Quel oiseau ne vole pas mais court très vite ?', 'autruche', new Date()),
        new QuizzCard('médecine', 'facile', 'assets/med.jpeg', 'Quel organe est affecté par l’hépatite ?', 'foie', new Date()),
        new QuizzCard('science et technologie', 'facile', 'assets/sci_tech.jpg', 'Quel est l’unité de mesure de la résistance électrique ?', 'ohm', new Date()),
        new QuizzCard('histoire', 'difficile', 'assets/histo.jpg', 'Quel roi a été guillotiné pendant la Révolution française ?', 'louis xvi', new Date()),
        new QuizzCard('botanique', 'expert', 'assets/bota.jpeg', 'Quel arbre produit des glands ?', 'chêne', new Date()),
        new QuizzCard('zoo', 'moyenne', 'assets/zoo.jpeg', 'Quel animal a une bosse et vit dans le désert ?', 'chameau', new Date()),
        new QuizzCard('géographie', 'moyenne', 'assets/geo.jpg', 'Dans quel pays se trouve la ville de Kyoto ?', 'japon', new Date()),
        new QuizzCard('science et technologie', 'génie', 'assets/sci_tech.jpg', 'Quelle planète est la plus proche du soleil ?', 'mercure', new Date()),
        new QuizzCard('histoire', 'facile', 'assets/histo.jpg', 'En quelle année a eu lieu la Révolution française ?', '1789', new Date()),
        new QuizzCard('médecine', 'génie', 'assets/med.jpeg', 'Quel est l’os le plus long du corps humain ?', 'fémur', new Date()),
        new QuizzCard('zoo', 'difficile', 'assets/zoo.jpeg', 'Quel est le cri du coq ?', 'chant', new Date()),
        new QuizzCard('botanique', 'moyenne', 'assets/bota.jpeg', 'Quel gaz les plantes absorbent-elles ?', 'dioxyde de carbone', new Date()),
        new QuizzCard('science et technologie', 'difficile', 'assets/sci_tech.jpg', 'Quel élément chimique a pour symbole Au ?', 'or', new Date()),
        new QuizzCard('histoire', 'génie', 'assets/histo.jpg', 'Quel est le nom de la célèbre bataille de 1066 ?', 'hastings', new Date()),
        new QuizzCard('géographie', 'facile', 'assets/geo.jpg', 'Quel est le plus grand fleuve du monde ?', 'nil', new Date()),
        new QuizzCard('médecine', 'moyenne', 'assets/med.jpeg', 'Quel est le groupe sanguin universel ?', 'o-', new Date()),
        new QuizzCard('science et technologie', 'expert', 'assets/sci_tech.jpg', 'Quel est le langage de programmation utilisé pour la majorité des sites web ?', 'javascript', new Date()),
        new QuizzCard('zoo', 'facile', 'assets/zoo.jpeg', 'Quel est le plus grand oiseau vivant ?', 'autruche', new Date()),
        new QuizzCard('botanique', 'facile', 'assets/bota.jpeg', 'Quelle est la partie comestible de la pomme de terre ?', 'tubercule', new Date()),
        new QuizzCard('histoire', 'moyenne', 'assets/histo.jpg', 'Qui était le roi d’Angleterre pendant la Première Guerre mondiale ?', 'george v', new Date()),
        new QuizzCard('science et technologie', 'moyenne', 'assets/sci_tech.jpg', 'De quel matériau est fait le fil dans une ampoule électrique ?', 'tungstène', new Date()),
        new QuizzCard('zoo', 'moyenne', 'assets/zoo.jpeg', 'Quel est le plus gros prédateur terrestre ?', 'ours polaire', new Date()),
        new QuizzCard('géographie', 'difficile', 'assets/geo.jpg', 'Dans quelle mer se jette le fleuve Danube ?', 'mer noire', new Date()),
        new QuizzCard('botanique', 'génie', 'assets/bota.jpeg', 'Quel est le nom du processus par lequel les plantes fabriquent leur nourriture ?', 'photosynthèse', new Date()),
        new QuizzCard('histoire', 'expert', 'assets/histo.jpg', 'Quelle guerre a eu lieu entre 1914 et 1918 ?', 'première guerre mondiale', new Date()),
        new QuizzCard('science et technologie', 'moyenne', 'assets/sci_tech.jpg', 'Qui a découvert la pénicilline ?', 'alexander fleming', new Date()),
        new QuizzCard('zoo', 'difficile', 'assets/zoo.jpeg', 'Quel animal possède le plus gros cerveau ?', 'baleine', new Date()),
        new QuizzCard('géographie', 'génie', 'assets/geo.jpg', 'Dans quelle ville se trouve le Colisée ?', 'rome', new Date()),
        new QuizzCard('botanique', 'facile', 'assets/bota.jpeg', 'Quel fruit produit un noyau ?', 'pêche', new Date()),
        new QuizzCard('science et technologie', 'facile', 'assets/sci_tech.jpg', 'Quel est le plus grand satellite naturel de la Terre ?', 'lune', new Date()),
        new QuizzCard('histoire', 'génie', 'assets/histo.jpg', 'Qui était le dirigeant de l’Union soviétique pendant la Seconde Guerre mondiale ?', 'staline', new Date()),
        new QuizzCard('zoo', 'facile', 'assets/zoo.jpeg', 'Quel est l’animal symbole de l’Australie ?', 'kangourou', new Date()),
        new QuizzCard('médecine', 'expert', 'assets/med.jpeg', 'Quel est le principal organe touché par la cirrhose ?', 'foie', new Date()),
        new QuizzCard('botanique', 'difficile', 'assets/bota.jpeg', 'Quelle est la plus grande fleur du monde ?', 'rafflesia arnoldii', new Date()),
        new QuizzCard('science et technologie', 'génie', 'assets/sci_tech.jpg', 'Qui a formulé les lois du mouvement ?', 'newton', new Date()),
        new QuizzCard('histoire', 'moyenne', 'assets/histo.jpg', 'En quelle année a eu lieu la chute du mur de Berlin ?', '1989', new Date()),
        new QuizzCard('géographie', 'facile', 'assets/geo.jpg', 'Quel est le pays le plus vaste du monde ?', 'russie', new Date()),
        new QuizzCard('zoo', 'expert', 'assets/zoo.jpeg', 'Quel est le plus grand prédateur marin ?', 'orque', new Date()),
        new QuizzCard('médecine', 'difficile', 'assets/med.jpeg', 'Quel est le nom de l’hormone produite par la glande thyroïde ?', 'thyroxine', new Date()),
        new QuizzCard('science et technologie', 'expert', 'assets/sci_tech.jpg', 'Quel est le plus grand télescope spatial lancé par la NASA ?', 'hubble', new Date()),
        new QuizzCard('botanique', 'moyenne', 'assets/bota.jpeg', 'De quel type d’arbre provient le sirop d’érable ?', 'érable', new Date()),
        new QuizzCard('science et technologie', 'facile', 'assets/sci_tech.jpg', 'Quelle est la principale source d\'énergie de la Terre ?', 'soleil', new Date()),
        new QuizzCard('histoire', 'difficile', 'assets/histo.jpg', 'Qui était le leader de l\'Empire ottoman pendant la Première Guerre mondiale ?', 'enver pacha', new Date()),
        new QuizzCard('botanique', 'expert', 'assets/bota.jpeg', 'Quelle plante produit des graines comestibles appelées "pignons" ?', 'pin', new Date()),
        new QuizzCard('zoo', 'génie', 'assets/zoo.jpeg', 'Quel animal est le plus rapide sur terre ?', 'guépard', new Date()),
        new QuizzCard('géographie', 'facile', 'assets/geo.jpg', 'Quel est le plus grand océan du monde ?', 'pacifique', new Date()),
        new QuizzCard('médecine', 'moyenne', 'assets/med.jpeg', 'Quel est le nom de la maladie causée par une carence en vitamine C ?', 'scorbut', new Date()),
        new QuizzCard('science et technologie', 'moyenne', 'assets/sci_tech.jpg', 'Quel pays a lancé le premier satellite artificiel ?', 'urss', new Date()),
        new QuizzCard('histoire', 'moyenne', 'assets/histo.jpg', 'En quelle année a eu lieu la bataille de Waterloo ?', '1815', new Date()),
        new QuizzCard('botanique', 'moyenne', 'assets/bota.jpeg', 'Quel arbre est réputé pour ses fruits qui produisent des noix ?', 'noyer', new Date()),
        new QuizzCard('zoo', 'facile', 'assets/zoo.jpeg', 'Quel animal vit dans l\'Antarctique et est un excellent nageur ?', 'manchot', new Date()),
        new QuizzCard('géographie', 'moyenne', 'assets/geo.jpg', 'Dans quelle ville se trouve la célèbre place Rouge ?', 'moscou', new Date()),
        new QuizzCard('science et technologie', 'génie', 'assets/sci_tech.jpg', 'Qui est le père de la théorie de la relativité ?', 'einstein', new Date()),
        new QuizzCard('médecine', 'facile', 'assets/med.jpeg', 'Quel est le type de médecin spécialisé en chirurgie cardiaque ?', 'cardiologue', new Date()),
        new QuizzCard('histoire', 'expert', 'assets/histo.jpg', 'Quel fut le dernier tsar de Russie ?', 'nicholas ii', new Date()),
        new QuizzCard('botanique', 'difficile', 'assets/bota.jpeg', 'Quelle plante est utilisée pour produire le chocolat ?', 'cacaoyer', new Date()),
        new QuizzCard('zoo', 'moyenne', 'assets/zoo.jpeg', 'Quel animal est connu pour sa mémoire exceptionnelle ?', 'éléphant', new Date()),
        new QuizzCard('géographie', 'génie', 'assets/geo.jpg', 'Quel est le plus petit pays du monde ?', 'vatican', new Date()),
        new QuizzCard('science et technologie', 'difficile', 'assets/sci_tech.jpg', 'Quel est le plus grand ordinateur quantique existant ?', 'sycamore', new Date()),
        new QuizzCard('médecine', 'génie', 'assets/med.jpeg', 'Quel est l\'organisme responsable de la grippe ?', 'virus de la grippe', new Date()),
        new QuizzCard('histoire', 'génie', 'assets/histo.jpg', 'Qui a signé l\'indépendance des États-Unis en 1776 ?', 'thomas jefferson', new Date()),
        new QuizzCard('botanique', 'facile', 'assets/bota.jpeg', 'Quel arbre est principalement utilisé pour fabriquer des meubles ?', 'chêne', new Date()),
        new QuizzCard('zoo', 'facile', 'assets/zoo.jpeg', 'Quel animal est souvent appelé "le roi de la jungle" ?', 'lion', new Date()),
        new QuizzCard('géographie', 'moyenne', 'assets/geo.jpg', 'Dans quelle ville se trouve la Tour Eiffel ?', 'paris', new Date()),
        new QuizzCard('science et technologie', 'moyenne', 'assets/sci_tech.jpg', 'Quel est le nom de la première voiture produite en série ?', 'ford t', new Date()),
        new QuizzCard('médecine', 'moyenne', 'assets/med.jpeg', 'Quel organe est responsable de la production d\'insuline ?', 'pancréas', new Date()),
        new QuizzCard('histoire', 'facile', 'assets/histo.jpg', 'Qui était le leader des nazis pendant la Seconde Guerre mondiale ?', 'hitler', new Date()),
        new QuizzCard('botanique', 'moyenne', 'assets/bota.jpeg', 'Quelle plante est couramment utilisée pour l\'aromatisation du thé ?', 'menthe', new Date()),
        new QuizzCard('zoo', 'difficile', 'assets/zoo.jpeg', 'Quel est le plus petit oiseau au monde ?', 'colibri', new Date()),
        new QuizzCard('géographie', 'génie', 'assets/geo.jpg', 'Quel est le plus grand pays d\'Afrique ?', 'algérie', new Date()),
        new QuizzCard('science et technologie', 'facile', 'assets/sci_tech.jpg', 'Quel appareil utilise des lentilles pour grossir les objets ?', 'microscope', new Date()),
        new QuizzCard('médecine', 'difficile', 'assets/med.jpeg', 'Quel est le nom de la technique qui permet de soigner la cataracte ?', 'chirurgie de la cataracte', new Date()),
        new QuizzCard('histoire', 'moyenne', 'assets/histo.jpg', 'Qui était le premier président des États-Unis ?', 'george washington', new Date()),
        new QuizzCard('botanique', 'expert', 'assets/bota.jpeg', 'Quel arbre produit des châtaignes ?', 'châtaignier', new Date()),
        new QuizzCard('zoo', 'génie', 'assets/zoo.jpeg', 'Quel est l\'animal terrestre le plus lourd ?', 'éléphant', new Date()),
        new QuizzCard('géographie', 'facile', 'assets/geo.jpg', 'Quel est le plus grand lac d\'Afrique ?', 'lac victoria', new Date()),
        new QuizzCard('science et technologie', 'moyenne', 'assets/sci_tech.jpg', 'Quelle est la plus grande entreprise de technologies au monde ?', 'apple', new Date()),
        new QuizzCard('médecine', 'génie', 'assets/med.jpeg', 'Quel est le nom de la maladie qui attaque le système nerveux central ?', 'sclérose en plaques', new Date()),
        new QuizzCard('histoire', 'difficile', 'assets/histo.jpg', 'Quel empire a été dirigé par Gengis Khan ?', 'empire mongol', new Date()),
        new QuizzCard('botanique', 'difficile', 'assets/bota.jpeg', 'Quel est le plus grand arbre du monde ?', 'séquoia', new Date()),
        new QuizzCard('zoo', 'moyenne', 'assets/zoo.jpeg', 'Quel animal est le plus grand carnivore terrestre ?', 'ours polaire', new Date()),
        new QuizzCard('géographie', 'génie', 'assets/geo.jpg', 'Quel est le point le plus bas sur Terre ?', 'mer morte', new Date()),
        new QuizzCard('science et technologie', 'génie', 'assets/sci_tech.jpg', 'Quel est l\'inventeur du téléphone ?', 'alexander graham bell', new Date()),
        new QuizzCard('médecine', 'facile', 'assets/med.jpeg', 'Comment s\'appelle la maladie qui provoque une accumulation de sucre dans le sang ?', 'diabète', new Date()),
        new QuizzCard('géographie', 'difficile', 'assets/geo.jpg', 'Quel est le plus grand océan du monde ?', 'pacifique', new Date()),
        new QuizzCard('zoo', 'moyenne', 'assets/zoo.jpeg', 'Quel animal est connu pour ses tâches blanches et noires ?', 'zèbre', new Date()),
        new QuizzCard('science et technologie', 'expert', 'assets/sci_tech.jpg', 'Quel est le nom de la première voiture électrique produite en masse ?', 'tesla model s', new Date()),
        new QuizzCard('botanique', 'génie', 'assets/bota.jpeg', 'Quel est le nom de la plus grande plante carnivore ?', 'nepenthes', new Date()),
        new QuizzCard('médecine', 'moyenne', 'assets/med.jpeg', 'Quel est le nom du virus responsable du sida ?', 'vih', new Date()),
        new QuizzCard('histoire', 'moyenne', 'assets/histo.jpg', 'Quand la Première Guerre mondiale a-t-elle commencé ?', '1914', new Date()),
        new QuizzCard('science et technologie', 'moyenne', 'assets/sci_tech.jpg', 'Quel est le principal moteur de recherche internet ?', 'google', new Date()),
        new QuizzCard('zoo', 'génie', 'assets/zoo.jpeg', 'Quel est le seul mammifère capable de voler ?', 'chauve-souris', new Date()),
        new QuizzCard('géographie', 'facile', 'assets/geo.jpg', 'Quel est le pays le plus peuplé au monde ?', 'chine', new Date()),
        new QuizzCard('histoire', 'expert', 'assets/histo.jpg', 'Qui a dirigé l\'Empire mongol au XIIIe siècle ?', 'gengis khan', new Date()),
        new QuizzCard('botanique', 'difficile', 'assets/bota.jpeg', 'Quel est l\'autre nom du bambou géant ?', 'dendrocalamus', new Date()),
        new QuizzCard('science et technologie', 'facile', 'assets/sci_tech.jpg', 'De quelle matière est faite la coque d\'un smartphone ?', 'plastique', new Date()),
        new QuizzCard('zoo', 'facile', 'assets/zoo.jpeg', 'Quel animal est le plus grand primate ?', 'gorille', new Date()),
        new QuizzCard('médecine', 'difficile', 'assets/med.jpeg', 'Quel est le terme médical pour désigner une pression artérielle trop élevée ?', 'hypertension', new Date()),
        new QuizzCard('histoire', 'moyenne', 'assets/histo.jpg', 'Quel était le nom du navire qui a coulé en 1912 ?', 'titanic', new Date()),
        new QuizzCard('géographie', 'moyenne', 'assets/geo.jpg', 'Dans quel pays se trouve le Machu Picchu ?', 'pérou', new Date()),
        new QuizzCard('botanique', 'facile', 'assets/bota.jpeg', 'Quelle plante est utilisée pour fabriquer du thé ?', 'camellia sinensis', new Date()),
        new QuizzCard('science et technologie', 'génie', 'assets/sci_tech.jpg', 'Qui a créé le premier ordinateur mécanique ?', 'charles babbage', new Date()),
        new QuizzCard('zoo', 'moyenne', 'assets/zoo.jpeg', 'Quel est l\'animal symbole de l\'Australie ?', 'kangourou', new Date()),
        new QuizzCard('histoire', 'facile', 'assets/histo.jpg', 'Quel pays a été dirigé par Napoléon Bonaparte ?', 'france', new Date()),
        new QuizzCard('science et technologie', 'moyenne', 'assets/sci_tech.jpg', 'Quel est le langage de programmation utilisé pour les sites Web ?', 'html', new Date()),
        new QuizzCard('botanique', 'génie', 'assets/bota.jpeg', 'Quelle est la plus grande plante au monde ?', 'séquoia géant', new Date()),
        new QuizzCard('médecine', 'expert', 'assets/med.jpeg', 'Qu\'est-ce qui est utilisé pour détecter les cancers du sein ?', 'mammographie', new Date()),
        new QuizzCard('histoire', 'difficile', 'assets/histo.jpg', 'Qui a été le dernier roi de France avant la Révolution ?', 'louis xvi', new Date()),
        new QuizzCard('géographie', 'expert', 'assets/geo.jpg', 'Quel est le plus grand pays en superficie du monde ?', 'russie', new Date()),
        new QuizzCard('science et technologie', 'facile', 'assets/sci_tech.jpg', 'Qui a inventé l\'ampoule électrique ?', 'thomas edison', new Date()),
        new QuizzCard('botanique', 'moyenne', 'assets/bota.jpeg', 'De quelle plante provient le coton ?', 'cotonnier', new Date()),
        new QuizzCard('zoo', 'facile', 'assets/zoo.jpeg', 'Quel est le plus grand oiseau vivant ?', 'autruche', new Date()),
        new QuizzCard('médecine', 'moyenne', 'assets/med.jpeg', 'Quelle maladie est causée par une carence en vitamine D ?', 'rachitisme', new Date()),
        new QuizzCard('histoire', 'génie', 'assets/histo.jpg', 'Qui a rédigé la Déclaration des droits de l\'homme en 1789 ?', 'louis xvi', new Date()),
        new QuizzCard('science et technologie', 'expert', 'assets/sci_tech.jpg', 'Qui a découvert l\'électromagnétisme ?', 'hanne oersted', new Date()),
        new QuizzCard('botanique', 'expert', 'assets/bota.jpeg', 'Quel est le plus grand groupe d\'arbres au monde ?', 'conifères', new Date()),
        new QuizzCard('zoo', 'moyenne', 'assets/zoo.jpeg', 'Quel est l\'animal qui a la plus grande longévité ?', 'tortue', new Date()),
        new QuizzCard('géographie', 'difficile', 'assets/geo.jpg', 'Quel est le plus long fleuve d\'Asie ?', 'yangzi', new Date()),
        new QuizzCard('science et technologie', 'génie', 'assets/sci_tech.jpg', 'Qui a inventé la première machine à écrire ?', 'william sholes', new Date()),
        new QuizzCard('médecine', 'facile', 'assets/med.jpeg', 'Quel est le terme médical pour désigner une température élevée ?', 'fièvre', new Date()),
        new QuizzCard('histoire', 'difficile', 'assets/histo.jpg', 'Quel est le nom de la première dynastie de Chine ?', 'dynastie qin', new Date()),
        new QuizzCard('botanique', 'difficile', 'assets/bota.jpeg', 'Quel arbre produit des figues ?', 'figuier', new Date()),
        new QuizzCard('zoo', 'génie', 'assets/zoo.jpeg', 'Quel est l\'animal qui peut hiberner pendant des mois ?', 'marmotte', new Date()),
        new QuizzCard('géographie', 'facile', 'assets/geo.jpg', 'Quel pays se trouve sur les deux continents, l\'Europe et l\'Asie ?', 'turquie', new Date()),
        new QuizzCard('science et technologie', 'génie', 'assets/sci_tech.jpg', 'Qui a mis au point la première loi de la thermodynamique ?', 'rudolf clausius', new Date()),
        new QuizzCard('botanique', 'génie', 'assets/bota.jpeg', 'Quel est le plus grand genre de plantes ?', 'caryophyllaceae', new Date()),
        new QuizzCard('médecine', 'difficile', 'assets/med.jpeg', 'Quel est le nom de la maladie qui affecte le système nerveux central et perturbe la coordination ?', 'ataxie', new Date()),
        new QuizzCard('histoire', 'moyenne', 'assets/histo.jpg', 'En quelle année a eu lieu la Première Guerre mondiale ?', '1914', new Date()),
        new QuizzCard('science et technologie', 'difficile', 'assets/sci_tech.jpg', 'Quel est le premier satellite envoyé dans l\'espace ?', 'spoutnik', new Date()),
        new QuizzCard('géographie', 'moyenne', 'assets/geo.jpg', 'Quel est le plus grand désert du monde ?', 'sahara', new Date()),
        new QuizzCard('médecine', 'moyenne', 'assets/med.jpeg', 'Quel est le nom du virus responsable de la varicelle ?', 'varicelle', new Date()),
        new QuizzCard('histoire', 'génie', 'assets/histo.jpg', 'Qui était le dernier empereur d\'Égypte ?', 'cleopatre', new Date()),
        new QuizzCard('botanique', 'facile', 'assets/bota.jpeg', 'Quelle plante est utilisée pour fabriquer du vin ?', 'raisin', new Date()),
        new QuizzCard('zoo', 'moyenne', 'assets/zoo.jpeg', 'Quel animal est le plus grand reptile sur Terre ?', 'crocodile', new Date()),
        new QuizzCard('science et technologie', 'expert', 'assets/sci_tech.jpg', 'Quel est le nom de la première programmation informatique ?', 'fortran', new Date()),
        new QuizzCard('histoire', 'facile', 'assets/histo.jpg', 'Qui a été le premier président des États-Unis ?', 'george washington', new Date()),
        new QuizzCard('botanique', 'génie', 'assets/bota.jpeg', 'Quel est le plus grand groupe d\'arbres au monde ?', 'séquoias', new Date()),
        new QuizzCard('zoo', 'difficile', 'assets/zoo.jpeg', 'Quel est l\'animal dont le cœur bat à un rythme particulièrement lent ?', 'tortue', new Date()),
        new QuizzCard('géographie', 'expert', 'assets/geo.jpg', 'Quel est le pays le plus au nord du monde ?', 'islande', new Date()),
        new QuizzCard('science et technologie', 'facile', 'assets/sci_tech.jpg', 'Qui a inventé le premier téléphone ?', 'alexander graham bell', new Date()),
        new QuizzCard('histoire', 'moyenne', 'assets/histo.jpg', 'En quelle année l\'Empire romain a-t-il été fondé ?', '27 av. j.-c.', new Date()),
        new QuizzCard('botanique', 'moyenne', 'assets/bota.jpeg', 'De quelle plante provient l\'huile essentielle utilisée pour l\'aromathérapie ?', 'lavande', new Date()),
        new QuizzCard('zoo', 'génie', 'assets/zoo.jpeg', 'Quel est l\'animal ayant la plus grande espérance de vie ?', 'tortue géante des seychelles', new Date()),
        new QuizzCard('médecine', 'moyenne', 'assets/med.jpeg', 'Quelle est la principale cause de l\'ulcère de l\'estomac ?', 'bactérie h. pylori', new Date()),
        new QuizzCard('science et technologie', 'difficile', 'assets/sci_tech.jpg', 'Quel est le nom de la sonde spatiale qui a exploré Pluton ?', 'new horizons', new Date()),
        new QuizzCard('géographie', 'facile', 'assets/geo.jpg', 'Dans quelle ville se trouve la célèbre place Saint-Marc ?', 'venise', new Date()),
        new QuizzCard('histoire', 'expert', 'assets/histo.jpg', 'En quelle année la Révolution française a-t-elle commencé ?', '1789', new Date()),
        new QuizzCard('botanique', 'facile', 'assets/bota.jpeg', 'Quel fruit est aussi appelé "pomme de terre sucrée" ?', 'patate douce', new Date()),
        new QuizzCard('zoo', 'moyenne', 'assets/zoo.jpeg', 'Quel animal est connu pour sa grande mémoire et son comportement social complexe ?', 'éléphant', new Date()),
        new QuizzCard('science et technologie', 'génie', 'assets/sci_tech.jpg', 'Quel inventeur a créé le premier moteur à combustion interne ?', 'nikolaus otto', new Date()),
        new QuizzCard('géographie', 'difficile', 'assets/geo.jpg', 'Quel est le plus grand lac du continent asiatique ?', 'lac caspienne', new Date()),
        new QuizzCard('histoire', 'moyenne', 'assets/histo.jpg', 'Quel événement marque la fin de la Seconde Guerre mondiale ?', 'capitulation de l\'allemagne', new Date()),
        new QuizzCard('botanique', 'moyenne', 'assets/bota.jpeg', 'Quel arbre est communément associé à la culture japonaise ?', 'cerisier', new Date()),
        new QuizzCard('zoo', 'facile', 'assets/zoo.jpeg', 'Quel animal est connu pour sa lenteur et porte sa maison sur son dos ?', 'escargot', new Date()),
        new QuizzCard('science et technologie', 'expert', 'assets/sci_tech.jpg', 'Qui a inventé la première machine à calculer programmable ?', 'charles babbage', new Date()),
        new QuizzCard('médecine', 'facile', 'assets/med.jpeg', 'Quel organe est responsable de la production d\'insuline ?', 'pancréas', new Date()),
        new QuizzCard('histoire', 'génie', 'assets/histo.jpg', 'Quel est le nom du dernier pharaon de l\'Égypte ancienne ?', 'cleopatre', new Date()),
        new QuizzCard('botanique', 'difficile', 'assets/bota.jpeg', 'Quel arbre est le plus grand producteur de bois dans le monde ?', 'pin', new Date()),
        new QuizzCard('zoo', 'difficile', 'assets/zoo.jpeg', 'Quel est le plus gros poisson au monde ?', 'requin baleine', new Date()),
        new QuizzCard('géographie', 'génie', 'assets/geo.jpg', 'Quel est le pays avec le plus grand nombre d\'îles ?', 'suède', new Date()),
        new QuizzCard('science et technologie', 'moyenne', 'assets/sci_tech.jpg', 'Quel est le nom du premier moteur de recherche internet ?', 'yahoo', new Date()),
        new QuizzCard('histoire', 'moyenne', 'assets/histo.jpg', 'En quelle année a eu lieu la chute du mur de Berlin ?', '1989', new Date()),
        new QuizzCard('botanique', 'génie', 'assets/bota.jpeg', 'Quel est l\'arbre le plus vieux au monde ?', 'pin de bristlecone', new Date()),
        new QuizzCard('zoo', 'expert', 'assets/zoo.jpeg', 'Quel est l\'oiseau le plus rapide en vol ?', 'faucon pèlerin', new Date()),
        new QuizzCard('médecine', 'génie', 'assets/med.jpeg', 'Quel est le nom du premier vaccin développé par Edward Jenner ?', 'vaccin contre la variole', new Date()),
        new QuizzCard('géographie', 'facile', 'assets/geo.jpg', 'Quel est le plus grand pays du monde en superficie ?', 'russie', new Date()),
        new QuizzCard('science et technologie', 'difficile', 'assets/sci_tech.jpg', 'Quel est le nom du premier téléphone portable ?', 'motorola dynatac', new Date()),
        new QuizzCard('histoire', 'difficile', 'assets/histo.jpg', 'Quel pays a été dirigé par Mao Zedong ?', 'chine', new Date()),
        new QuizzCard('botanique', 'moyenne', 'assets/bota.jpeg', 'Quel arbre produit des noix utilisées dans les pâtisseries ?', 'noisetier', new Date()),
        new QuizzCard('zoo', 'moyenne', 'assets/zoo.jpeg', 'Quel est l\'animal connu pour son long cou ?', 'girafe', new Date()),
        new QuizzCard('science et technologie', 'génie', 'assets/sci_tech.jpg', 'Qui a inventé le premier moteur à vapeur ?', 'james watt', new Date()),
        new QuizzCard('médecine', 'moyenne', 'assets/med.jpeg', 'Quel est le terme médical désignant la fracture d\'un os ?', 'fracture', new Date()),
        new QuizzCard('histoire', 'génie', 'assets/histo.jpg', 'Qui était le dernier tsar de Russie ?', 'nicholas ii', new Date()),
        new QuizzCard('botanique', 'génie', 'assets/bota.jpeg', 'Quel est l\'autre nom du tronc d\'un arbre ?', 'colonne', new Date()),
        new QuizzCard('zoo', 'génie', 'assets/zoo.jpeg', 'Quel est l\'animal le plus intelligent ?', 'dauphin', new Date()),
        new QuizzCard('histoire', 'moyenne', 'assets/histo.jpg', 'Quel était le nom du navire qui a coulé en 1912 ?', 'titanic', new Date()),
        new QuizzCard('botanique', 'facile', 'assets/bota.jpeg', 'Quelle plante est utilisée pour fabriquer du thé ?', 'camellia sinensis', new Date()),
        new QuizzCard('science et technologie', 'facile', 'assets/sci_tech.jpg', 'De quelle matière est faite la coque d\'un smartphone ?', 'plastique', new Date()),
        new QuizzCard('science et technologie', 'expert', 'assets/sci_tech.jpg', 'Qui a inventé la première machine à calculer programmable ?', 'charles babbage', new Date()),
        new QuizzCard('zoo', 'moyenne', 'assets/zoo.jpeg', 'Quel est l\'animal symbole de l\'Australie ?', 'kangourou', new Date()),
        new QuizzCard('géographie', 'difficile', 'assets/geo.jpg', 'Quel est le plus grand lac du continent asiatique ?', 'lac caspienne', new Date()),
        new QuizzCard('science et technologie', 'génie', 'assets/sci_tech.jpg', 'Qui a créé le premier ordinateur mécanique ?', 'charles babbage', new Date()),
        new QuizzCard('médecine', 'difficile', 'assets/med.jpeg', 'Quel est le terme médical pour désigner une température élevée ?', 'fièvre', new Date()),
        new QuizzCard('histoire', 'facile', 'assets/histo.jpg', 'Qui a été le premier président des États-Unis ?', 'george washington', new Date()),
        new QuizzCard('botanique', 'facile', 'assets/bota.jpeg', 'Quelle plante est utilisée pour fabriquer du vin ?', 'raisin', new Date()),
        new QuizzCard('zoo', 'génie', 'assets/zoo.jpeg', 'Quel est le plus grand animal terrestre ?', 'éléphant', new Date()),
        new QuizzCard('science et technologie', 'génie', 'assets/sci_tech.jpg', 'Quel est le nom de la première mission humaine sur la Lune ?', 'apollo 11', new Date()),
        new QuizzCard('géographie', 'facile', 'assets/geo.jpg', 'Dans quel pays se trouve la Tour Eiffel ?', 'france', new Date()),
        new QuizzCard('science et technologie', 'difficile', 'assets/sci_tech.jpg', 'Qui a développé la première caméra numérique ?', 'steven sasson', new Date()),
        new QuizzCard('histoire', 'expert', 'assets/histo.jpg', 'Quel événement marqua la fin de l\'Empire romain ?', 'chute de rome', new Date()),
        new QuizzCard('médecine', 'facile', 'assets/med.jpeg', 'Quel est l\'organe responsable de la production d\'insuline ?', 'pancréas', new Date()),
        new QuizzCard('science et technologie', 'moyenne', 'assets/sci_tech.jpg', 'Quel est le nom du premier moteur de recherche internet ?', 'google', new Date()),
        new QuizzCard('botanique', 'difficile', 'assets/bota.jpeg', 'Quel est le nom scientifique du cannabis ?', 'cannabis sativa', new Date()),
        new QuizzCard('zoo', 'moyenne', 'assets/zoo.jpeg', 'Quel est le plus grand oiseau vivant ?', 'autruche', new Date()),
        new QuizzCard('science et technologie', 'génie', 'assets/sci_tech.jpg', 'Quel inventeur est reconnu pour avoir développé le premier télégraphe électrique ?', 'samuel morse', new Date()),
        new QuizzCard('géographie', 'expert', 'assets/geo.jpg', 'Quel est le plus grand archipel du monde ?', 'indonésie', new Date()),
        new QuizzCard('histoire', 'moyenne', 'assets/histo.jpg', 'Quel est le nom du dictateur nazi responsable de la Seconde Guerre mondiale ?', 'adolf hitler', new Date()),
        new QuizzCard('science et technologie', 'difficile', 'assets/sci_tech.jpg', 'Qui est le fondateur de Microsoft ?', 'bill gates', new Date()),
        new QuizzCard('zoo', 'expert', 'assets/zoo.jpeg', 'Quel est l\'animal qui possède la plus grande taille de dents sur Terre ?', 'narval', new Date()),
        new QuizzCard('botanique', 'moyenne', 'assets/bota.jpeg', 'Quelle plante est utilisée pour fabriquer des médicaments contre le paludisme ?', 'quinquina', new Date()),
        new QuizzCard('science et technologie', 'facile', 'assets/sci_tech.jpg', 'Quel est le nom du premier ordinateur personnel ?', 'apple i', new Date()),
        new QuizzCard('géographie', 'moyenne', 'assets/geo.jpg', 'Quel pays est le plus grand producteur de café ?', 'brésil', new Date()),
        new QuizzCard('histoire', 'facile', 'assets/histo.jpg', 'Quel était le nom de la première guerre mondiale ?', 'première guerre mondiale', new Date()),
        new QuizzCard('science et technologie', 'génie', 'assets/sci_tech.jpg', 'Qui a découvert l\'électromagnétisme ?', 'hans christian oersted', new Date()),
        new QuizzCard('botanique', 'génie', 'assets/bota.jpeg', 'Quel est le plus grand groupe d\'arbres au monde ?', 'séquoia géant', new Date()),
        new QuizzCard('médecine', 'génie', 'assets/med.jpeg', 'Quel est le nom de la bactérie responsable de la tuberculose ?', 'mycobacterium tuberculosis', new Date()),
        new QuizzCard('histoire', 'génie', 'assets/histo.jpg', 'Quel pharaon a fait construire les pyramides de Gizeh ?', 'khéops', new Date()),
        new QuizzCard('zoo', 'facile', 'assets/zoo.jpeg', 'Quel est le plus grand mammifère marin ?', 'baleine bleue', new Date()),
        new QuizzCard('géographie', 'moyenne', 'assets/geo.jpg', 'Quel est le plus grand pays d\'Amérique du Sud ?', 'brésil', new Date()),
        new QuizzCard('botanique', 'moyenne', 'assets/bota.jpeg', 'Quel arbre produit des noix utilisées dans les pâtisseries ?', 'noisetier', new Date()),
        new QuizzCard('science et technologie', 'difficile', 'assets/sci_tech.jpg', 'Quel est le nom de la première sonde spatiale envoyée à Jupiter ?', 'pioneer 10', new Date()),
        new QuizzCard('zoo', 'génie', 'assets/zoo.jpeg', 'Quel est l\'animal connu pour sa grande capacité à imiter des sons humains ?', 'perroquet', new Date()),
        new QuizzCard('géographie', 'difficile', 'assets/geo.jpg', 'Quel est le plus grand lac d\'eau douce en volume ?', 'lac baïkal', new Date()),
        new QuizzCard('histoire', 'moyenne', 'assets/histo.jpg', 'Quel était le nom du premier empereur de Chine ?', 'qin shi huang', new Date()),
        new QuizzCard('science et technologie', 'facile', 'assets/sci_tech.jpg', 'Qui a inventé le téléphone portable ?', 'martin cooper', new Date()),
        new QuizzCard('médecine', 'moyenne', 'assets/med.jpeg', 'Quelle est la principale fonction des globules blancs ?', 'défendre contre les infections', new Date()),
        new QuizzCard('botanique', 'expert', 'assets/bota.jpeg', 'Quel est l\'arbre le plus grand du monde ?', 'séquoia géant', new Date()),
        new QuizzCard('science et technologie', 'moyenne', 'assets/sci_tech.jpg', 'Qui a inventé l\'ampoule électrique ?', 'thomas edison', new Date()),
        new QuizzCard('géographie', 'facile', 'assets/geo.jpg', 'Quel est le pays avec le plus grand nombre d\'îles ?', 'suède', new Date()),
        new QuizzCard('histoire', 'difficile', 'assets/histo.jpg', 'En quelle année l\'Empire romain a-t-il été fondé ?', '27 av. j.-c.', new Date()),
        new QuizzCard('zoo', 'facile', 'assets/zoo.jpeg', 'Quel est l\'animal le plus grand reptile sur Terre ?', 'crocodile', new Date()),
        new QuizzCard('science et technologie', 'génie', 'assets/sci_tech.jpg', 'Qui a mis au point la première loi de la thermodynamique ?', 'rudolf clausius', new Date()),
        new QuizzCard('botanique', 'facile', 'assets/bota.jpeg', 'Quel fruit est aussi appelé "pomme de terre sucrée" ?', 'patate douce', new Date()),
        new QuizzCard('science et technologie', 'facile', 'assets/sci_tech.jpg', 'Qui a inventé le premier téléphone ?', 'alexander graham bell', new Date()),
        new QuizzCard('zoo', 'moyenne', 'assets/zoo.jpeg', 'Quel est l\'animal connu pour sa grande mémoire et son comportement social complexe ?', 'éléphant', new Date()),
        new QuizzCard('science et technologie', 'génie', 'assets/sci_tech.jpg', 'Quel inventeur a créé le premier moteur à combustion interne ?', 'nikolaus otto', new Date()),
        new QuizzCard('botanique', 'moyenne', 'assets/bota.jpeg', 'De quelle plante provient l\'huile essentielle utilisée pour l\'aromathérapie ?', 'lavande', new Date()),
        new QuizzCard('médecine', 'moyenne', 'assets/med.jpeg', 'Quelle maladie est causée par une carence en vitamine D ?', 'rachitisme', new Date()),
        new QuizzCard('géographie', 'difficile', 'assets/geo.jpg', 'Quel est le plus long fleuve d\'Asie ?', 'yangzi', new Date()),
        new QuizzCard('science et technologie', 'moyenne', 'assets/sci_tech.jpg', 'Quel est le langage de programmation utilisé pour les sites Web ?', 'html', new Date()),
        new QuizzCard('histoire', 'facile', 'assets/histo.jpg', 'Qui a été le premier président des États-Unis ?', 'george washington', new Date()),
        new QuizzCard('botanique', 'moyenne', 'assets/bota.jpeg', 'De quelle plante provient l\'huile essentielle utilisée pour l\'aromathérapie ?', 'lavande', new Date()),
        new QuizzCard('zoo', 'génie', 'assets/zoo.jpeg', 'Quel est l\'animal ayant la plus grande espérance de vie ?', 'tortue géante des seychelles', new Date()),
        new QuizzCard('science et technologie', 'difficile', 'assets/sci_tech.jpg', 'Quel est le nom de la sonde spatiale qui a exploré Pluton ?', 'new horizons', new Date()),
        new QuizzCard('géographie', 'facile', 'assets/geo.jpg', 'Dans quelle ville se trouve la célèbre place Saint-Marc ?', 'venise', new Date()),
        new QuizzCard('histoire', 'moyenne', 'assets/histo.jpg', 'En quelle année l\'Empire romain a-t-il été fondé ?', '27 av. j.-c.', new Date()),
        new QuizzCard('botanique', 'moyenne', 'assets/bota.jpeg', 'De quelle plante provient l\'huile essentielle utilisée pour l\'aromathérapie ?', 'lavande', new Date()),
        new QuizzCard('zoo', 'facile', 'assets/zoo.jpeg', 'Quel est le plus grand oiseau vivant ?', 'autruche', new Date()),
        new QuizzCard('science et technologie', 'expert', 'assets/sci_tech.jpg', 'Quel est le nom de la première mission humaine sur la Lune ?', 'apollo 11', new Date()),
        new QuizzCard('géographie', 'difficile', 'assets/geo.jpg', 'Quel est le plus grand désert du monde ?', 'sahara', new Date()),
        new QuizzCard('science et technologie', 'difficile', 'assets/sci_tech.jpg', 'Quel est le nom du premier moteur de recherche internet ?', 'google', new Date()),
        new QuizzCard('histoire', 'expert', 'assets/histo.jpg', 'Quel événement marque la fin de la Seconde Guerre mondiale ?', 'capitulation de l\'allemagne', new Date()),
        new QuizzCard('botanique', 'facile', 'assets/bota.jpeg', 'Quel fruit est aussi appelé "pomme de terre sucrée" ?', 'patate douce', new Date()),
        new QuizzCard('science et technologie', 'facile', 'assets/sci_tech.jpg', 'Qui a inventé l\'ampoule électrique ?', 'thomas edison', new Date()),
        new QuizzCard('médecine', 'moyenne', 'assets/med.jpeg', 'Quel organe est responsable de la production d\'insuline ?', 'pancréas', new Date()),
        new QuizzCard('zoo', 'difficile', 'assets/zoo.jpeg', 'Quel est l\'animal dont le cœur bat à un rythme particulièrement lent ?', 'tortue', new Date()),
        new QuizzCard('géographie', 'expert', 'assets/geo.jpg', 'Quel est le pays le plus au nord du monde ?', 'islande', new Date()),
        new QuizzCard('science et technologie', 'moyenne', 'assets/sci_tech.jpg', 'Quel est le langage de programmation utilisé pour les sites Web ?', 'html', new Date()),
        new QuizzCard('science et technologie', 'difficile', 'assets/sci_tech.jpg', 'Quel est le premier satellite envoyé dans l\'espace ?', 'spoutnik', new Date()),
        new QuizzCard('zoo', 'moyenne', 'assets/zoo.jpeg', 'Quel animal est le plus grand reptile sur Terre ?', 'crocodile', new Date()),
        new QuizzCard('botanique', 'génie', 'assets/bota.jpeg', 'Quel est le plus grand groupe d\'arbres au monde ?', 'séquoias', new Date()),
        new QuizzCard('science et technologie', 'génie', 'assets/sci_tech.jpg', 'Qui a inventé la première machine à écrire ?', 'william sholes', new Date()),
        new QuizzCard('histoire', 'moyenne', 'assets/histo.jpg', 'Quel événement marque la fin de la Seconde Guerre mondiale ?', 'capitulation de l\'allemagne', new Date()),
        new QuizzCard('science et technologie', 'facile', 'assets/sci_tech.jpg', 'Qui a inventé le téléphone ?', 'alexander graham bell', new Date()),
        new QuizzCard('histoire', 'facile', 'assets/histo.jpg', 'Qui a été le premier président des États-Unis ?', 'george washington', new Date()),
        new QuizzCard('science et technologie', 'difficile', 'assets/sci_tech.jpg', 'Quel est le nom du premier moteur de recherche internet ?', 'google', new Date()),
        new QuizzCard('botanique', 'moyenne', 'assets/bota.jpeg', 'De quelle plante provient l\'huile essentielle utilisée pour l\'aromathérapie ?', 'lavande', new Date()),
        new QuizzCard('zoo', 'moyenne', 'assets/zoo.jpeg', 'Quel animal est le plus grand reptile sur Terre ?', 'crocodile', new Date()),
        new QuizzCard('science et technologie', 'génie', 'assets/sci_tech.jpg', 'Quel inventeur a créé le premier moteur à combustion interne ?', 'nikolaus otto', new Date())
        
    ];

    getQuizzCards() : QuizzCard[]{
        return [...this.quizzCards]
    }

    getQuizzCardId(id : number){
        const foundquizzcard = this.quizzCards.find(quizzcard =>quizzcard.id===id);
        if(!foundquizzcard)
            return ''
        else
            return foundquizzcard;
    }

}